### ISSUE TITLE
UI notification for failed test of alert and destinations

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/alerting#100]
<a href="https://github.com/renegaderyu"><img src="https://avatars.githubusercontent.com/u/1818590?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [renegaderyu](https://github.com/renegaderyu)**
_Wednesday May 19, 2021 at 17:16 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/alerting/issues/378_

----

**Is your feature request related to a problem? Please describe.**
There is no indication from the UI that a test notification has failed to send to the destination.
It is not possible to test a destination w/o trying to configure an alert.

**Describe the solution you'd like**
A pop-up alert for failures to test the alert.
Ability to test destinations separately from alerts

**Comment by aditjind** [comment]
By design we don't throw an exception whenever we are not able to send an alert. We mark that alert in the error state and send that error as a part of the response of the monitor execution result. Since the monitor execution succeeds the response doesn't throw any error and in the [frontend code](https://github.com/opensearch-project/alerting-dashboards-plugin/blob/main/public/pages/CreateTrigger/containers/ConfigureActions/ConfigureActions.js#L116) we check for the response status of the request and not the status of the action (which is present in the response content). This results in the front end not showing an error for the action which was not executed. 

This implementation is correct from the backend as the monitor execution succeeded and the action should be marked in the error state. The problem lies in the front-end response parsing where we should check explicitly for the action response.

**Comment by qreshi** [comment]
Closing this issue since the fix was merged on Alerting Dashboards
