### ISSUE TITLE
[BUG] Upgrading from OpenSearch 1.3 to 2.5 causes monitor names to disappear from UI

### ISSUE THREAD

**Issue by sbcd90** [opensearch-project/alerting#1060]
**What is the bug?**
Upgrading from OpenSearch 1.3 to 2.5 causes monitor names to disappear from UI(or show as null).

**How can one reproduce the bug?**
1. Go to 'List monitors'
2. See error - name is null or not shown
3. Select the monitor & click on Edit
4. Name shows correctly

**What is the expected behavior?**
the Monitor list should show names of all monitors correctly.

**What is your host/environment?**
 - Version 2.5
 - Plugins

**Comment by AWSHurneyt** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/1030
