### ISSUE TITLE
Support alerts on audit logs

### ISSUE THREAD

**Issue by praveensameneni** [opensearch-project/alerting#108]
OpenSearch is used to store and search large volumes of data. OpenSearch audit logs maintain a record of user activity of the system.  In conjunction with appropriate tools and procedures, audit logs can provide a means to help accomplish several security-related objectives, including individual accountability, reconstruction of events, intrusion detection, and problem analysis [NIST-CSRC (https://csrc.nist.gov/csrc/media/publications/shared/documents/itl-bulletin/itlbul1997-03.txt)].
Provide an out-of-box solution that helps OpenSearch administrators to analyze Users activity. The first version (P0) of this project is completely out-of-box and doesn’t require any new release of OpenSearch.  This solution provides new dashboards that gets insights into Users activity, a set of monitors that create alerts based on abnormal User activity, and a set of Saved Queries for ad-hoc exploration.

**Comment by brijos** [comment]
@praveensameneni I don't believe this is planned for 2.0 correct?

**Comment by ict-one-nl** [comment]
Would be appreciated. We are collecting logs from different instances through a webhook to logstash to a central opensearch cluster. Would be nice to be able to alert there as well.

**Comment by lezzago** [comment]
The [Security Analytics plugin](https://github.com/opensearch-project/security-analytics/) takes care of these kind of use cases, so will be closing this issue in favor of users utilizing that plugin.

**Comment by ict-one-nl** [comment]
Shouldn't the issue be moved?
