### ISSUE TITLE
[BUG] Acknowledging an alert prevents the monitor ever from firing again

### ISSUE THREAD

**Issue by krsouthern** [opensearch-project/alerting#1085]
**What is the bug?**
Using version 2.7 or 2.9 and having configured a monitor and trigger, if you then acknowledge an alert, the status of the monitor becomes acknowledged but then the monitor never fires again for the trigger condition.

There are some posts that suggest this may be the expected behaviour but we would expect the status of the trigger to eventually become completed or for it to alert again possibly, which it doesn't. It remains in a stuck state (screenshot below).

If we delete the trigger from the monitor and re-add it, then alerts then appear to reset and fire again.

**Do you have any screenshots?**
<img width="1071" alt="Screenshot 2023-08-11 at 14 48 45" src="https://github.com/opensearch-project/alerting/assets/465944/488cdbf4-4c50-4f08-b2c3-38c15ad6f6eb">

**Comment by lezzago** [comment]
If the trigger condition was constantly being satisfied, it would not go to a completed state, so that it would fire an alert again. 

Have you verified if the trigger condition should not be satisfied and it is still showing the alert is acknowledged?

**Comment by krsouthern** [comment]
That makes sense, thank you for confirming that is the expected behaviour.

I believe the alerts were still firing at this point so that would explain why it remained acknowledged.

>>Have you verified if the trigger condition should not be satisfied and it is still showing the alert is acknowledged?

Yes, I've retested this now to ensure the condition isn't firing again in the given timeframe and it's set to completed, so thats working as expected.
