### ISSUE TITLE
[BUG] Polluting log entry regarding destination migration

### ISSUE THREAD

**Issue by spapadop** [opensearch-project/alerting#1183]
**What is the bug?**
There is a specific log that keeps on appearing quite frequently on all OpenSearch clusters (even fresh installations). While it does not somehow harm the cluster, its consistent presence is quite annoying:

```
[INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [my-node-name] Detected cluster change event for destination migration
```

I tracked this message on [DestinationMigrationCoordinator.kt](https://github.com/opensearch-project/alerting/blob/main/alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/DestinationMigrationCoordinator.kt#L48). I am not sure what is exactly wrong there, but something is.

There are couple of related threads already on the forums, like [here](https://forum.opensearch.org/t/detected-cluster-change-event-for-destination-migration/11871) and [here](https://forum.opensearch.org/t/opensearch-upgrade-leftover-persistent-settings/10877/5?u=spapadop). 

And if you google "Detected cluster change event for destination migration", you'll see that it appears on many logs, for unrelated issues, so my guess is that it's just polluting logs.

**How can one reproduce the bug?**
Just bootstrap a new cluster and check the output logs.

**What is the expected behavior?**
Not to produce such a polluting log.

**What is your host/environment?**
 - OpenSearch: v2.9.0
 - OS: AlmaLinux 9.2
 - Plugins: all that come by default

**Comment by IAmFQQ** [comment]
Yeah, I met the same issue, such logs are very annoying. I can't even find out which components printed it from the source code.

**Comment by spapadop** [comment]
still there in v2.11

**Comment by riysaxen-amzn** [comment]
closing in favor of #1356

**Comment by uranru** [comment]
version 2.13
the problem persists

![изображение](https://github.com/opensearch-project/alerting/assets/44777964/07c4941c-960b-4b3c-a45b-a7a5a7d15c67)

**Comment by Its-Ankush** [comment]
Can confirm i see this all the time [in OS_2.16]
```
[2024-09-20T09:23:18,647][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [data_node_1] Cancelling the migration process.
[2024-09-20T09:23:42,440][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [data_node_1] Cancelling the migration process.
[2024-09-20T09:23:43,819][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [data_node_1] Cancelling the migration process.
[2024-09-20T09:23:43,920][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [data_node_1] Cancelling the migration process.
```

**Comment by mousemaxx** [comment]
OS 2.17, messages still in log

**Comment by spapadop** [comment]
@riysaxen-amzn could you please reopen this issue? Or shall we create a new one?
The original reported problem is not fixed by https://github.com/opensearch-project/alerting/pull/1356

btw, there is a suggestion there: https://github.com/opensearch-project/alerting/pull/1356#issuecomment-2355029957

**Comment by tallyoh** [comment]
Can report that it still happens in 2.16 - Is there a new issue for this?

**Comment by jkrishnarao2003** [comment]
we upgraded our cluster from 2.10.0 to 2.18.0 last week.  We see bunch of logs every often with message "Cancelling the migration process."  Is this a bug or issue with our upgrade?

**Comment by aliSadegh** [comment]
same issue, at the node start, there are bunch of messages "Cancelling the migration process.", recently we upgraded form 2.13.0 to 2.17.1.
is there any problem?

**Comment by cinhtau** [comment]
Still in 2.19.1 - poor quality

We suppress it with

```
PUT _cluster/settings
{
  "persistent": {
    "logger": {
      "org": {
        "opensearch": { 
          "alerting.util.destinationmigration.DestinationMigrationCoordinator": "WARN"
        }
      }
    }
  }
}
```

**Comment by mattttv** [comment]
still in 2.19.2
