### ISSUE TITLE
Alerts should be visible to users who have access to the tenant

### ISSUE THREAD

**Issue by aimtsou** [opensearch-project/alerting#119]
**Is your feature request related to a problem? Please describe.**
Since we have the multi-tenancy it will be important for each user in the alerting plugin(dashboards, monitors, destinations) to be able to define the options and has access to rules for the tenants that he belongs to. Consequently:

1) The alerting dashboard has only your own alerts and you do not search for them
2) Your alerts page contains your own alerts and nobody from another tenant can access and/or modify them
3) Destinations also are belonging to the user/s of the tenant

**Describe the solution you'd like**
Alerting package should belong only to the users of each tenant. If user1 has access to tenant1 then he sees the alerts configured for tenant1. If user1 has access to tenant1 and to tenant2, according to which tenant he has chosen, then considering his rights he is able to see and modify the alerts for this specific tenant.

**Describe alternatives you've considered**
No alternatives at the moment but we consider this an important enhancement

**Comment by aimtsou** [comment]
Another addition to this, when choosing your own index then the list displaying the indices should be limited to your tenant only besides you are an admin as described here https://github.com/opensearch-project/alerting/issues/139

Generally an admin should be able to see everything.

**Comment by skkosuri-amzn** [comment]
@aimtsou Currently, OpenSearch-Dashboard-tenancy is for OpenSearch-Dashboard objects like dashboard, saved queries and few more. Alerting objects are not OpenSearch-Dashboard objects, you can group users using permissions/roles/backend roles while using Alerting. There is no plan to extend OpenSearch-Dashboard-tenancy to OpenSearch constructs like Alerting.

**Comment by aimtsou** [comment]
But permissions in Alerting allow read/write to users, they do not allow index-based usage.
Putting it differently, you cannot offer tenancy in dashboard / visualizations but all the rest of the elements to be open to everybody as they can be combined with the information from dashboards.

**Comment by JujuElk** [comment]
Hi @brijos and @skkosuri-amzn, this enhancement of Alerting plugin could be great for us as well. Do you have any update concerning the backlog of this feature ?
