### ISSUE TITLE
Editing a Per Bucket Monitor loses the Group By expressions

### ISSUE THREAD

**Issue by krsouthern** [opensearch-project/alerting#1200]
**What is the bug?**

When you edit a Per Bucket Monitor the Group by expressions are not re-populated.

<img width="2090" alt="Screenshot 2023-09-22 at 09 06 35" src="https://github.com/opensearch-project/alerting/assets/465944/1b1a5928-82e9-4d2a-bbc2-a3d1625e7242">

when you click edit on the monitor, the saved values are not displayed
<img width="2094" alt="Screenshot 2023-09-22 at 09 06 14" src="https://github.com/opensearch-project/alerting/assets/465944/46ce6b3c-72cd-418e-88bd-6859f3637f34">

**How can one reproduce the bug?**
1. Create a new Per Bucket Monitor
2. Add some group by expressions in the Query box
3. Save the Monitor
4. Edit the Monitor
5. The Group by expressions are lost

**What is the expected behavior?**
The Group by expressions should displayed on the screen

**What is your host/environment?**
 - Browser: Safari and Chrome on Mac

**Do you have any screenshots?**
added screenshots above

**Do you have any additional context?**
Add any other context about the problem.

**Comment by eirsep** [comment]
This is an alerting dashboards issue. Created the same issue there: https://github.com/opensearch-project/alerting-dashboards-plugin/issues/858
