### ISSUE TITLE
[BUG] Flaky tests in SecureWorkflowRestApiIT

### ISSUE THREAD

**Issue by AWSHurneyt** [opensearch-project/alerting#1246]
**What is the bug?**
This PR calls out that he tests in `SecureWorkflowRestApiIT` are flaky when executed in the Jenkins CI. The flakiness will need to be investigated and resolved.
https://github.com/opensearch-project/alerting/pull/1166

The `@Ignore` annotation was causing the integ tests to fail with the following error. This PR changes the annotation to the recommended `@AwaitsFix`.
https://github.com/opensearch-project/alerting/pull/1245
```
> Task :alerting:forbiddenApisTest FAILED
Forbidden annotation use: org.junit.Ignore [Use AwaitsFix instead]
  in org.opensearch.alerting.resthandler.SecureWorkflowRestApiIT (SecureWorkflowRestApiIT.kt, annotation on class declaration)
Scanned 120 class file(s) for forbidden API invocations (in 0.38s), 1 error(s).

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':alerting:forbiddenApisTest'.
> de.thetaphi.forbiddenapis.ForbiddenApiException: Check for forbidden API calls failed, see log.
```

**Comment by riysaxen-amzn** [comment]
closing in favor of #1245
