### ISSUE TITLE
Remove `.opendistro-alerting-alert*` indices from system-indices configuration

### ISSUE THREAD

**Issue by skkosuri-amzn** [opensearch-project/alerting#125]
**Is your feature request related to a problem? Please describe.**
Remove `.opendistro-alerting-alert*` indices from system-indices configuration by default.

**Describe the solution you'd like**
`.opendistro-alerting-alert*` indices contains current and historical alerts. Currently, `.opendistro-alerting-alert*` indices are configured as [system-index](https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/system-indices/) by default. To access these indices, you must authenticate with an admin certificate. Though system-indices provide greater privileges requirements to directly access these indices, but at the same time users can't build visualizations and dashboards on top of these indices.

Proposal:

Remove `.opendistro-alerting-alert*` indices from system-indices configuration by default. Still the access to these indices are controlled by roles. This would enable building visualizations and dashboards on top of these indices.
And at the same time, secure access is controlled by security roles rather than system-indices.

**Describe alternatives you've considered**
Edit OpenSearch.yml file and remove `.opendistro-alerting-alert*` from `opendistro_security.system_indices.indices`. 

**Additional context**
Similar proposal for `.opendistro-anomaly-results*` indices which store results of the Anomaly Detection plugin generated results.

**Comment by skkosuri-amzn** [comment]
Tagging @kaituo @ylwu-amzn @lezzago

**Comment by skkosuri-amzn** [comment]
Tagging more folks: @elfisher @praveensameneni

**Comment by elfisher** [comment]
@skkosuri-amzn does this retain the index, but just remove it from system indices? What is the impact to the user? Would they now need specific permission policies to access these indices? thx!

**Comment by kaituo** [comment]
@skkosuri-amzn Is removing the alert index the only action needed?

**Comment by ylwu-amzn** [comment]
> @skkosuri-amzn does this retain the index, but just remove it from system indices? What is the impact to the user? Would they now need specific permission policies to access these indices? thx!

@elfisher @skkosuri-amzn 
I think any user who has permission of alerting index can read/write/delete the index directly, of course admin user will be able to do anything. Generally, current users can still use alerting plugin via Kibana&API like before. Moving alerting index out of system index makes it possible to allow user who has specific security roles can query the index directly, like @skkosuri-amzn  said, that can "enable building visualizations and dashboards on top of these indices", which is impossible as no one including admin user can query system indices directly.

**Comment by skkosuri-amzn** [comment]
> @skkosuri-amzn does this retain the index, but just remove it from system indices? What is the impact to the user? Would they now need specific permission policies to access these indices? thx!

@elfisher - Yes, it removes from system-indices configuration. Users with priviliges can access alerts (stored in `.opendistro-alerting-alert*` indices from both direct API as `GET /.opendistro-alerting-alert*/_search` and also using alerting api `GET _opendistro/_alerting/monitors/alerts` , with system-indices users can use only `GET _opendistro/_alerting/monitors/alerts` to read alerts. Only `super-admin` is able to access with direct API when these indices are configured as system-indices.

**Comment by skkosuri-amzn** [comment]
> @skkosuri-amzn Do we only need to remove the alert index from system index list in security plugin? Do we need anything else? Does that mean we accept no fine-grained access control on the alert index?

@kaituo Yes, remove alerts* indices from opensearch.yml config for system-indices. We need to double check, if we need to  modify default alerts roles. We still have fine-grained access control on these indices, we plan to remove only from system-index config. These indices still require privileges (roles) to access data form these indices.

**Comment by hardik-k-shah** [comment]
As discussed, we should only remove indices (from system index) on which specific plugin doesn't depend for its operation/configuration. 

No user (including admin) should have direct access on any indices which store configurations or data on which plugin directly operates. Those indices should be part of system index and any modification on that indices should be allowed only via APIs exposed through plugin. 

Indices which are configuration index and or indices which data plugin consumes for its operation should not be exposed to any user (except super admin). So, any accidental changes to these indices can be avoided. 

In alerting case, if I understand correctly, the index mentioned in above issues stores only historical alerts and alerting plugin operations doesn't directly depends on history of the alerts and hence it is safe to remove that index out of system index.

**Comment by skkosuri-amzn** [comment]
Yes @hardik-k-shah This indices we plan to remove from system-indices list contain only alerts history.

**Comment by skkosuri-amzn** [comment]
Hi @all, This is targeted for next release of OpenSearch 1.1.

**Comment by ryn9** [comment]
@skkosuri-amzn @hardik-k-shah would direct modification of .opendistro-alerting-alert* or .opendistro-anomaly-results* cause issues with the alerting or anomaly plugins?

For example - for alerting - what are the impacts of the following?
A document for an alert is deleted
A document for an alert is modified such that one of heuristics is modified: 
  eg.
  monitor_user.name
  monitor_user.backend_roles
  monitor_user.roles
  trigger_id
  trigger_name
  state
  error_message
  alert_history
  severity
  action_execution_results
  start_time
  last_notification_time
  end_time
  acknowledged_time

Additionally - what guidance will be provided regarding fgac on these indices? 
For example - in a multi-tenant model I suspect that folks would want to apply some type of field level security for roles access these indices?

**Comment by qreshi** [comment]
> In alerting case, if I understand correctly, the index mentioned in above issues stores only historical alerts and alerting plugin > operations doesn't directly depends on history of the alerts and hence it is safe to remove that index out of system index.

@hardik-k-shah @skkosuri-amzn The `.opendistro-alerting-alert-history*` is the historical Alert history but the `.opendistro-alerting-alerts` index contains active Alert information and is being used during Monitor execution runtime to determine new Alert states and update existing ones. Removing that as a system index would break the recommended format Hardik is suggesting.

**Comment by skkosuri-amzn** [comment]
> > In alerting case, if I understand correctly, the index mentioned in above issues stores only historical alerts and alerting plugin > operations doesn't directly depends on history of the alerts and hence it is safe to remove that index out of system index.
> 
> @hardik-k-shah @skkosuri-amzn The `.opendistro-alerting-alert-history*` is the historical Alert history but the `.opendistro-alerting-alerts` index contains active Alert information and is being used during Monitor execution runtime to determine new Alert states and update existing ones. Removing that as a system index would break the recommended format Hardik is suggesting.

@hardik-k-shah is suggesting that all plugin related configuraton must be in opensearch-system-index.  Since `.opendistro-alerting-alerts` contains generated alerts not plugin related configuration, I think its fine to remove from system-indices.

**Comment by skkosuri-amzn** [comment]
@ryn9  Please fnd my response inline.

> A document for an alert is deleted

If an alert (doc) is deleted, this is no impact on monitors. That alert is removed from the system forever. 

> A document for an alert is modified such that one of heuristics is modified:
> eg.
> monitor_user.name
> monitor_user.backend_roles
> monitor_user.roles
> trigger_id
> trigger_name
> state
> error_message
> alert_history
> severity
> action_execution_results
> start_time
> last_notification_time
> end_time
> acknowledged_time

We should probably change default alerting roles using [field level security](https://opensearch.org/docs/security-plugin/access-control/field-level-security/) to provide the following
* Filter `monitor_user` for both `read` and `write`.
* Enable `read-only` for all fields expect `state` (`state` is required to ack)

`admin` will have all_access.

> Additionally - what guidance will be provided regarding fgac on these indices?
> For example - in a multi-tenant model I suspect that folks would want to apply some type of field level security for roles access these indices?

In multi-tenant model, we can filter alerts by `monitor_user.backend_roles` using [document-level-security](https://opensearch.org/docs/security-plugin/access-control/document-level-security/)

**Comment by kaituo** [comment]
@skkosuri-amzn @ylwu-amzn   is there any backward compatibility we need to after removing the index?  Can we remove AD code in alerting after that?

**Comment by qreshi** [comment]
@skkosuri-amzn Technically speaking, I believe @hardik-k-shah's exact words were:
> No user (including admin) should have direct access on any indices which store configurations or data on which plugin **directly operates**.

We do directly operate on the `.opendistro-alerting-alerts` index and did only allow the one user-required write to this index (acknowledging alerts) to only be done through API. So we would be breaking the "operating" part of that agreement. I'm not necessarily disagreeing for the removal of it as a system index but just want to consider all the implications.

If some user operation were to cause Alerting to be unable to read from the `opendistro-alerting-alerts`, it's possible it can cause the Monitor to go into an error state. Can users currently not close system indices and will removing it as one make that a possibility? Just want to think through the worst case failure modes this opens up before proceeding.

**Comment by skkosuri-amzn** [comment]
Based on the above discussion, we want to keep `.opendistro-alerting-alerts` as system-index. No change is planned for this. OpenSearch users still can change this behaviour by changing [opensearch.yml](https://github.com/opensearch-project/security/blob/main/securityconfig/opensearch.yml.example#L233) config.
