### ISSUE TITLE
[BUG] Flaky test AlertingBackwardsCompatibilityIT.test backwards compatibility

### ISSUE THREAD

**Issue by eirsep** [opensearch-project/alerting#1266]
https://github.com/opensearch-project/alerting/actions/runs/6501182782/job/17658255304

**Comment by engechas** [comment]
Spot checking a few of the most recent runs, it doesn't appear this test is flaky anymore. We are taking a wholistic look at the flakiness in the CIs that should address these types of issues. Will close this issue in favor of that
