### ISSUE TITLE
[FEATURE] Show key string in monitor UI for per bucket monitor

### ISSUE THREAD

**Issue by atammy-narmi** [opensearch-project/alerting#1282]
**Is your feature request related to a problem?**
When creating a per bucket monitor and an alert getting triggered, the monitor only has the trigger name in the monitor UI. This makes it impossible to distinguish alerts by what bucket they are referring to. It would be helpful to have a distinguishing feature per bucket in the UI.

Like for the following alert where it monitors VPN healths, I got alerts for 10 VPN health checks which failed and while I can acknowledge them individually, I can't tell which one I am acknowledging.
<img width="1408" alt="alerts-photo" src="https://github.com/opensearch-project/alerting/assets/116575891/ebab6287-d527-4354-ab63-668cf87b7282">

**What solution would you like?**
Add the per bucket string in the UI for a per bucket monitor.

**What alternatives have you considered?**
Any other distinguishing feature for the buckets would work as well.

**Comment by praveensameneni** [comment]
We introduced the above enhancement in 2.13
PR: https://github.com/opensearch-project/alerting/pull/1450
Here's an example of how to show sample documents
{{#ctx.alerts}}
    Sample documents:
    {{#sample_documents}}
        Index: {{_index}}
        Document ID: {{_id}}
       
        Order date: {{_source.order_date}}
        Order ID: {{_source.order_id}}
        Clothing category: {{_source.category}}
        -----------------
    {{/sample_documents}}
{{/ctx.alerts}}
