### ISSUE TITLE
[BUG] "info deleteOldIndices" labeled as ERROR instead of INFO

### ISSUE THREAD

**Issue by cpockrandt** [opensearch-project/alerting#1303]
**Describe the bug**

The official OpenSearch 2.11.0 docker container logs the following messages as ERROR messages:

```json
{
  "timestamp": "2023-11-15T22:16:49,232Z",
  "level": "ERROR",
  "component": "o.o.a.a.AlertIndices",
  "message": "info deleteOldIndices"
}
```

**To Reproduce**

I have a pretty vanilla installation of OpenSearch 2.11.0 running in the official Docker image (deployed with Helm). Logging is configured to output in JSON:

```yaml
opensearch.config.log4j2.properties: |
      status = error

      appender.console.type = Console
      appender.console.name = console
      appender.console.layout.type = OpenSearchJsonLayout
      appender.console.layout.type_name = server

      rootLogger.level = "{{ default "Info" .Values.global.logLevel }}"
      rootLogger.appenderRef.console.ref = console
```

**Expected behavior**

It should be logged as INFO.

**Comment by StewartWBrown1** [comment]
Just to add, it looks like this was resolved in [this ticket here](https://github.com/opensearch-project/security-analytics/pull/203), but the backport to 2.x failed here and was never resolved: https://github.com/opensearch-project/security-analytics/pull/534

**Comment by StewartWBrown1** [comment]
Should be resolved now in https://github.com/opensearch-project/security-analytics/pull/833 as this has been successfully merged

**Comment by jowg-amazon** [comment]
This issue was merged and backported in these PRs
main: https://github.com/opensearch-project/security-analytics/pull/203
2.x: https://github.com/opensearch-project/security-analytics/pull/833
2.11: https://github.com/opensearch-project/security-analytics/pull/917
2.9: https://github.com/opensearch-project/security-analytics/pull/916

**Comment by cpockrandt** [comment]
@jowg-amazon Even with OpenSearch 2.13 and 2.14 I get the same behavior. Is it possible that the bug still hasn't been fully fixed?

**Comment by StewartWBrown1** [comment]
> @jowg-amazon Even with OpenSearch 2.13 and 2.14 I get the same behavior. Is it possible that the bug still hasn't been fully fixed?

There were two near-identical issues in different places in OpenSearch. The one at https://github.com/opensearch-project/security-analytics/pull/203 was fixed and had the 'info deleteOldIndices' printed in logs every 12 hours from 'o.o.s.i.DetectorIndexManagementService'. This is what has been merged and is in currently released OpenSearch versions. 

There was another source of the 'info deleteOldIndices' message from "o.o.a.a.AlertIndices". This is the one you reported and are seeing. It has finally been successfully backported to 2.x as of https://github.com/opensearch-project/alerting/pull/1230 so this error message should no longer be reported from OpenSearch 2.15!

**Comment by cpockrandt** [comment]
Thank you so much for the insight!
