### ISSUE TITLE
Provide ability to associate `backend role` and `security role` during monitor create

### ISSUE THREAD

**Issue by skkosuri-amzn** [opensearch-project/alerting#138]
**Is your feature request related to a problem? Please describe.**
Provide ability to associate `backend role` and `security role` during monitor create.

Currently, during monitor creation the user `backend roles` and `security roles` are resolved and associated with monitor. There is no option for the User to select which `backend role` and `security role` to get associated instead of all. 

**Describe the solution you'd like**
Provide optional field to add `backend role` and `security role` in the `POST _plugins/_alerting/monitors` API. When these optional fields are provided, and these are present in resolved roles - use provided roles to associate with monitor.

**Comment by ryn9** [comment]
@skkosuri-amzn is this expected to make its way into the 1.3 release?

**Comment by brijos** [comment]
@ryn9, this isn't gong to make it into 1.3.  We will update this issue when we know more about which release this will fall into.

**Comment by ryn9** [comment]
@brijos . thank you for letting me know. Please let me know if there is any additional information / context I can aide with.

**Comment by sevenval-admins** [comment]
Hi, any news here?

**Comment by ryn9** [comment]
@sevenval-admins - if you and folks you know are looking for this feature - please make sure they give is a thumbs up at the top.

**Comment by qreshi** [comment]
@lezzago Can we close this based on the PR linked above being merged in or is there any additional work to be done?

**Comment by lezzago** [comment]
We have updated the [documentation](https://opensearch.org/docs/latest/monitoring-plugins/alerting/api/#create-a-query-level-monitor) and starting from 2.4, we support allowing to specify backend roles.
