### ISSUE TITLE
[BUG] UI Bug on Actions input under a Trigger

### ISSUE THREAD

**Issue by melegar** [opensearch-project/alerting#1411]
**What is the bug?**
When typing in the actions message box on Microsoft Edge on a monitor, after typing a letter the cursor moves to the message subject field label and you can no longer type without clicking on the message box again.  

**How can one reproduce the bug?**
1. Create a new monitor or edit an existing monitor
2. Fill out all options, and create a new action
3. With the action open, type into the message textbox
4. after typing a letter the cursor will bounce to the message subject label.  

**What is the expected behavior?**
You should be able to type in the message box continuously without the cursor leaving the box.

**What is your host/environment?**
 - OS: AWS Opensearch Service / OpenSearch_2_11_R20231113-P2 (latest)
 - Version: v2.11.0
 - Plugins:  Alerting plugin in this case
 - Since it seems like a UI issue, I've seen the behavior on Microsoft Edge version 120.0.2210.167 and Google Chrome version 119.0.6045.160

**Do you have any screenshots?**
See before screenshot
![image](https://github.com/opensearch-project/alerting/assets/4399795/295c391c-b46f-4f2c-9d7b-67dddec82c5f)

After typing a letter:
![image](https://github.com/opensearch-project/alerting/assets/4399795/df4729f8-2a65-4e21-9d90-97c4010b3b43)

**Comment by kgcreative** [comment]
This may be related to this issue: https://github.com/opensearch-project/alerting-dashboards-plugin/issues/785

**Comment by AWSHurneyt** [comment]
Closing as issue was fixed with https://github.com/opensearch-project/alerting-dashboards-plugin/issues/785
