### ISSUE TITLE
Build fails on fresh checkout - ktlint failures

### ISSUE THREAD

**Issue by mch2** [opensearch-project/alerting#146]
A fresh checkout of this repo fails to build with this command due to ktlint:

```
./gradlew assemble --no-daemon --refresh-dependencies -DskipTests=true -Dopensearch.version=1.1.0 -Dbuild.snapshot=false
```

**Comment by dbbaughe** [comment]
Labelling as a bug, what PRs that introduced the ktlint errors should not have been able to go through. Perhaps CI is not requiring correct tasks to run..

**Comment by qreshi** [comment]
If we're talking about the CI approval tasks for the Alerting repo itself, those do catch ktlint failures (at least as of late, not sure if something was changed there) and as of #156 any newly introduced or existing ktlint formatting issues were updated and the build should pass (the commit before this had ktlint failures on the CI so I confirmed it wasn't a false positive pass).

**Comment by dbbaughe** [comment]
Yes CI approval tasks -> one of these should have run the ktlint task and failed so was curious how it got in and if there's an issue with our CI tasks that needs to be fixed.

**Comment by skkosuri-amzn** [comment]
I see `Task :ktlint` is being run as part of the `Gradle build`.  We need to make sure that `main` has a stable build. No further action is required on this. Closing.
