### ISSUE TITLE
[ACTION NEEDED] Fix flaky integration tests at distribution level

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/alerting#1501]
**What is the bug?**
It was observed in 2.13.0 and previous other releases that alerting manually signed off on the release for failing integration tests. See https://github.com/opensearch-project/opensearch-build/issues/4433#issuecomment-2026436873
The flakiness of the test runs take a lot of time from the release team to collect go/no-go decision and significantly lower the confidence in the release bundles.

**How can one reproduce the bug?**
1. Run integration testing for altering and see the failures. 
2. Issues can be reproduced using the steps declared in AUTOCUT issues for failed integration testing

**What is the expected behavior?**
Tests should be consistently passing.

**Do you have any additional context?**
Please note that this is a hard blocker for 2.14.0 release as per the discussion [here](https://github.com/opensearch-project/opensearch-build/issues/4588)

**Comment by bbarani** [comment]
@praveensameneni @eirsep Can you please provide your inputs?

**Comment by gaiksaya** [comment]
Adding 2.14.0 release manager @rishabh6788

**Comment by AWSHurneyt** [comment]
As mentioned in https://github.com/opensearch-project/alerting/issues/1517#issuecomment-2096928443, test `SecureMonitorRestApiIT.test create monitor with an user without index read role` appears to be flaky.
