### ISSUE TITLE
[BUG] ODFE Doc Link in "Create monitor"

### ISSUE THREAD

**Issue by ahopp** [opensearch-project/alerting#17]
**Describe the bug**
There is a references to OpenDistro in the alertiing CX. Specifically, "Check the performance of your query and make sure to follow best practices. Learn more" points to https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/ rather than https://docs-beta.opensearch.org/docs/alerting/.

**Other plugins installed**
N/A

**To Reproduce**
1. Click Alerting -> Monitors -> Create monitor
2. Click "Learn more"

**Expected behavior**
Should point to OpenSearch documentation. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9532728/119098584-d1d71c00-b9ca-11eb-8be5-9491413986d8.png)

**Additional context**
N/A

**Comment by aditjind** [comment]
The [link](https://github.com/opensearch-project/alerting-dashboards-plugin/blob/main/utils/constants.js#L25) to the documentation is correct. This was updated as a recent change. 

This is used [here](https://github.com/opensearch-project/alerting-dashboards-plugin/blob/main/public/pages/CreateMonitor/components/QueryPerformance/QueryPerformance.js#L42). Please feel free to open if required.
