### ISSUE TITLE
Use SNAPSHOT artifacts from maven for dependencies 

### ISSUE THREAD

**Issue by abbashus** [opensearch-project/alerting#183]
Since OpenSearch maven artifacts are now published on public [Maven repository](https://aws.oss.sonatype.org/content/repositories/snapshots/), allow a way for plugin developers to take a dependency on a -SHAPSHOT. Currently requires building OpenSearch and all dependencies, and publishing to local maven.

**Comment by dblock** [comment]
Closed via https://github.com/opensearch-project/alerting/pull/184
