### ISSUE TITLE
Alerting OpenSearch 1.2 changes

### ISSUE THREAD

**Issue by skkosuri-amzn** [opensearch-project/alerting#202]
**Is your feature request related to a problem? Please describe.**
These are planned  changes for Alerting in OpenSearch 1.2. 

~~1. Don't replace monitor backend role when update
    GitHub issue:~~ #128 
2.  Admin Users must be able to access all monitors
    GitHub issue: #139 
3. Filter User object info (if any) in all the APIs 
~~4. Alerting Monitors should be exportable/importable objects
    GitHub issue:~~ #120

_This is active list, please expect changes as we reach OpenSearch 1.2 release._

**Comment by ryn9** [comment]
@skkosuri-amzn @praveensameneni - is 138 going to be addressed in the 1.2.0 release?
https://github.com/opensearch-project/alerting/issues/138

**Comment by skkosuri-amzn** [comment]
@ryn9 #138 got moved out of the 1.2.0 release. We want to have both UI change and backend change together in the release. UI changes couldnt make it in 1.2.0 release time frame.

**Comment by ryn9** [comment]
> @ryn9 #138 got moved out of the 1.2.0 release. We want to have both UI change and backend change together in the release. UI changes couldnt make it in 1.2.0 release time frame.

Was very much hoping the API was going to be available in 1.2.0  :(
Is there a specific call out to this then in 1.3?

**Comment by peternied** [comment]
@skkosuri-amzn @praveensameneni What is the status of this issue `1.2.0` was declared feature complete per https://github.com/opensearch-project/alerting/issues/182

**Comment by skkosuri-amzn** [comment]
> > @ryn9 #138 got moved out of the 1.2.0 release. We want to have both UI change and backend change together in the release. UI changes couldnt make it in 1.2.0 release time frame.
> 
> Was very much hoping the API was going to be available in 1.2.0 :( Is there a specific call out to this then in 1.3?

@ryn9 Let me explore more options.

**Comment by skkosuri-amzn** [comment]
> @skkosuri-amzn @praveensameneni What is the status of this issue `1.2.0` was declared feature complete per #182

Yes
