### ISSUE TITLE
Add MacOS Support

### ISSUE THREAD

**Issue by dblock** [opensearch-project/alerting#215]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/96, add MacOS (Darwin) support.

- [ ] Passing CI on MacOS
- [ ] Documentation

**Comment by engechas** [comment]
Mac support was added a while back: https://github.com/opensearch-project/alerting/blob/main/.github/workflows/test-workflow.yml#L73

Closing as completed. Please reopen if there are still remaining items
