### ISSUE TITLE
Refactor security integration tests

### ISSUE THREAD

**Issue by skkosuri-amzn** [opensearch-project/alerting#219]
**Is your feature request related to a problem? Please describe.**
Refactor security integration tests.
Currently, there are two test classes that run security integration tests`SecureDestinationRestApiIT` and `SecureMonitorRestApiIT`. These have become complex to follow and change, refactor , simplify and add new.

**Describe the solution you'd like**
Refactor , simplify and add new tests.

**Comment by aditjind** [comment]
The helper function for the third bullet point already exists. [Reference](https://github.com/opensearch-project/alerting/blob/0351155af9646d2d75a49394db0c3f36d5cac538/alerting/src/main/kotlin/org/opensearch/alerting/transport/SecureTransportAction.kt#L109)
