### ISSUE TITLE
[META] Document Level Alerting

### ISSUE THREAD

**Issue by skkosuri-amzn** [opensearch-project/alerting#238]
**What problem are we solving?**
Document returning alerts provides the ability to alert on each document in the index. Additionally the document returning monitor ensures that between monitor executions, there is no gap or overlap in data being monitored. With the existing monitor types in Alerting (Query Level and Bucket Level), we alert on a summarized view on the data, however, we never know which are the specific documents or records in the index that are triggering an alert in the monitor. Document level alerts also solves a common frustration where there are monitoring gaps or data overlaps based on timestamps.  The new monitor type will alert based on each document.  The findings store metadata information to note all the documents that match the trigger conditions into a new index called the Findings index for later reference.

Users want to find the documents that match their fields value to a specific set of predefined values. Predefined values are defined as the rules and are typically in order of 100s to 1000s. One example is - find the log messages whose  field `source.address` value equals to  `15.15.15.15` and field `response.status` is `401:Access Denied`. This type of field level signature detection is common in security detections.

**How to set it up**
Setting up a document level monitor will be fairly similar to the other existing monitor types. To create a document returning monitor, you can run the following command:

Note - before the release of the feature, the model definition can slightly differ.
```
POST _plugins/_alerting/monitors
{
  "type": "monitor",
  "monitor_type": "doc_level_monitor",
  "name": "iad-monitor",
  "enabled": true,
  "createdBy": "chip",
  "schedule": {
    "period": {
      "interval": 1,
      "unit": "MINUTES"
    }
  },
  "inputs": [
    {
      "doc_level_input": {
        "description": "windows-powershell",
        "indices": [
          "test-logs"
        ],
        "queries": [
          {
            "id": "sigma-123",
            "query": "region:\"us-west-2\"",
            "tags": [
              "MITRE:8500"
            ],
          },
          {
            "id": "sigma-456",
            "query": "region:\"us-east-1\"",
            "tags": [
              "MITRE:8600"
            ],
          }
        ]
      }
    }
  ],
    "triggers": [ { "document_level_trigger": {
      "name": "test-trigger",
      "severity": "1",
      "condition": {
        "script": {
          "source": "'sigma-123' && !'sigma-456'",
          "lang": "painless"
        }
      },
      "actions": []
  }}]
}
```

**Limitations**

- If the index is being reindexed, the next few monitor execution runs until after it is reindexed will give incorrect results. After the index is done being reindexed, it will have one last run of incorrect/repeated results. After that, the new data coming to the index will be be monitored correctly by the document returning monitor.

**Comment by dblock** [comment]
@lezzago This is still going into 2.0?

**Comment by lezzago** [comment]
> @lezzago This is still going into 2.0?

@dblock Yes this is going into 2.0

**Comment by dblock** [comment]
@lezzago What's left to close this issue? If it's documentation, let's close this here?

**Comment by lezzago** [comment]
Closing issue as Document Level Alerting is feature complete for 2.0.
