### ISSUE TITLE
[BUG] Flakey tests in github workflows related to :alerting:alertingBwcCluster#twoThirdsUpgradedClusterTask

### ISSUE THREAD

**Issue by leeyun-amzn** [opensearch-project/alerting#241]
**Describe the bug**
The task `:alerting:alertingBwcCluster#twoThirdsUpgradedClusterTask` is flakey when executing the test workflow and multi-node test workflow. It sometimes fails, and sometimes succeeds on re-run.

**Other plugins installed**
None

**To Reproduce**
Running the test workflow and multi-node workflow

**Expected behavior**
Should not have flake behavior.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Using Github action in this repository.

**Additional context**
Log files:
For multi-node test workflow [logs_multi_node_bwc_flakey.zip](https://github.com/opensearch-project/alerting/files/7541970/logs_multi_node_bwc_flakey.zip)
 
For test workflow [logs_test_workflow_bwc_flakey.zip](https://github.com/opensearch-project/alerting/files/7541967/logs_test_workflow_bwc_flakey.zip)

**Comment by qreshi** [comment]
Closing as this has been resolved.
