### ISSUE TITLE
Deprecate the "Master" nomenclature

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/alerting#320]
**Is your feature request related to a problem? Please describe.**
[OpenSearch](https://github.com/opensearch-project/OpenSearch) repository is going to replace the terminology "master"with "cluster manager".
issue: https://github.com/opensearch-project/OpenSearch/issues/472#issuecomment-960298995, with the plan for its terminology replacement.

Although the existing usages with "master" will be supported in OpenSearch version 2.x to keep the backwards compatibility, please prepare for the nomenclature change in advance, and replace all the usages with "master" terminology in the code base.
All the OpenSearch REST APIs and settings that contain "master" terminology will be deprecated in 2.0, and alternative usages will be added.

**Describe the solution you'd like**
Replace the  terminology "master" with "cluster manager".

When being compatible with OpenSearch 2.0:
- [x] Replace "master" in code comment (https://github.com/opensearch-project/alerting/blob/1.3.1.0/core/src/main/kotlin/org/opensearch/alerting/core/JobSweeper.kt#L141 and https://github.com/opensearch-project/alerting/blob/1.3.1.0/alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt#L52)
- [ ] Replace "master" in local variable: `private var isMaster` -> `isClusterManager`

When being compatible with OpenSearch 3.0:
- Replace "master" in the reference to OpenSearh Java API
  - [ ] event.localNodeMaster() -> event.localNodeClusterManager() (https://github.com/opensearch-project/alerting/blob/2.1.0.0/alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/DestinationMigrationCoordinator.kt#L55) (new API is available in v2.2)
  - [ ] `import org.opensearch.action.support.master.AcknowledgedResponse` -> `import org.opensearch.action.support.clustermanager.AcknowledgedResponse` (new API not available yet)

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by dblock** [comment]
For 2.0, at a minimum please ensure that the plugin is not calling any deprecated APIs in core or another plugin, and confirm below, then remove the 2.0.0 label. If you have time, do the complete deprecation as described in this issue.

**Comment by anasalkouz** [comment]
@sbcd90 Can we consider this as done? or there is still pending effort?

**Comment by sbcd90** [comment]
@anasalkouz Currently, `alerting` is compatible with `2.0`. But I see this same issue also tracks status for compatibility with `3.0`. 
We can close it & create a new one for `3.0`.

**Comment by anasalkouz** [comment]
Thats fine, we added 3.0 label tag to track remaining effort. Thanks

**Comment by anasalkouz** [comment]
@sbcd90 what is the remaining effort here? could we target 2.3?

**Comment by sbcd90** [comment]
hi @anasalkouz , yes. we need to make few changes in code to incorporate the following changes.

- event.localNodeMaster() -> event.localNodeClusterManager() (https://github.com/opensearch-project/alerting/blob/2.1.0.0/alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/DestinationMigrationCoordinator.kt#L55) (new API is available in v2.2)

-  import org.opensearch.action.support.master.AcknowledgedResponse -> import org.opensearch.action.support.clustermanager.AcknowledgedResponse (new API not available yet)

It is a small change. However, the 2nd api is not available yet. i see a related issue for it: https://github.com/opensearch-project/OpenSearch/issues/3663

Should we make these changes when the 2nd api is available?

**Comment by anasalkouz** [comment]
AcknowledgedResponse is an exception and we will have separate issue to track it across all plugins on 3.0.
For now let's finish localNodeClusterManager and close this issue.

**Comment by sbcd90** [comment]
hi @anasalkouz , the PR #548 with necessary changes required are merged now. Closing this issue.
