### ISSUE TITLE
Change the "Blacklist / Whitelist" nomenclature

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/alerting#321]
**Is your feature request related to a problem? Please describe.**
[OpenSearch](https://github.com/opensearch-project/OpenSearch) repository is going to replace the terminology "blacklist / whitelist" with "denylist / allowlist".
issue: https://github.com/opensearch-project/OpenSearch/issues/1483, with the plan for its terminology replacement.

Although the existing usages with "blacklist / whitelist" will be supported in OpenSearch version 2.x to keep the backwards compatibility, please prepare for the nomenclature change in advance.

**Describe the solution you'd like**

When being compatible with OpenSearch 3.0:
- Replace "whitelist" in the reference to OpenSearh Java API (new APIs will only be available in version 3.0)
  - [ ] `import org.opensearch.painless.spi.Whitelist` -> `import org.opensearch.painless.spi.Allowlist` (https://github.com/opensearch-project/alerting/blob/2.3.0.0/alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt#L102)
  - [ ] `import org.opensearch.painless.spi.WhitelistLoader` -> `import org.opensearch.painless.spi.AllowlistLoader` (https://github.com/opensearch-project/alerting/blob/12.3.0.0/alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt#L102)
  - [ ] `override fun getContextWhitelists(): Map<ScriptContext<*>, List<Whitelist>>` -> `override fun getContextAllowlists(): Map<ScriptContext<*>, List<Allowlist>>` (https://github.com/opensearch-project/alerting/blob/2.3.0.0/alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt#L126)

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by tlfeng** [comment]
Update: All the reference of `whitelist` in the public Java API of OpenSearch has been changed to `allowlist` (in the commit https://github.com/opensearch-project/OpenSearch/commit/8f8909fd548dd6617a4d4cd57a9b06407f72a68f).
Please use the renamed classes from OpenSearch Java library, when being compatible with OpenSearch 3.0.
For example:
Rename the class names
```
import org.opensearch.painless.spi.Whitelist
import org.opensearch.painless.spi.WhitelistLoader
```
to
```
import org.opensearch.painless.spi.Allowlist
import org.opensearch.painless.spi.AllowlistLoader
```

**Comment by anasalkouz** [comment]
Java APIs completed and released on 2.2
Could you please complete the remaining part from your end? let's target 2.3 to remove all usages

**Comment by anasalkouz** [comment]
@sbcd90 could you look into this?

**Comment by anasalkouz** [comment]
@praveensameneni Could you confirm if there is any effort remaining for this? If yes, let's please target to finish it on 2.4. Otherwise, let's close the issue

**Comment by sbcd90** [comment]
hi @anasalkouz , i looked into this issue. Looks like, we dont have the alternate apis `allowLists` available in `2.x`. 
https://github.com/opensearch-project/OpenSearch/pull/4101#issuecomment-1211422500
https://github.com/opensearch-project/OpenSearch/issues/1683#issuecomment-1209659930

i saw in the `opensearch-core` codebase, changes are only available in `main` branch & it looks like its a breaking change.

**Comment by tlfeng** [comment]
@sbcd90 `alerting` repository has done with all changes required for 2.x release, and the remaining effort will be tracked in separate issue as part of 3.0. Thank you!

The remaining effort stands for the following Java APIs
```
Map<ScriptContext<?>, List<Whitelist>> getContextWhitelists()
 -> Map<ScriptContext<?>, List<Allowlist>> getContextAllowlists()

org.opensearch.painless.spi.Whitelist -> Allowlist
org.opensearch.painless.spi.WhitelistLoader -> AllowlistLoader
```

**Comment by sbcd90** [comment]
thanks a lot @tlfeng .

**Comment by tlfeng** [comment]
Probably you can change the label for this issue to `v3.0.0`, instead of me creating a new separate issue.

**Comment by sbcd90** [comment]
@tlfeng ok done.
