### ISSUE TITLE
[BUG] Security Integration tests are failing for 2.0

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/alerting#355]
**Describe the bug**
The security Integration tests are failing for 2.0. This is due to the [security plugin](https://github.com/opensearch-project/security/) not being upgraded to 2.0 yet, so the cluster with security for 2.0 cannot come up and causes the security integration tests to fail.

**Other plugins installed**
Security plugin

**Expected behavior**
Once the security plugin has upgraded to 2.0, the tests should pass. If not, more investigation will then be required.

**Comment by getsaurabh02** [comment]
Related to https://github.com/opensearch-project/alerting/pull/354

**Comment by sbcd90** [comment]
Issue resolved by PR #407 . Closing this issue.
