### ISSUE TITLE
META - Push Based Alerts

### ISSUE THREAD

**Issue by brijos** [opensearch-project/alerting#397]
**Is your feature request related to a problem? Please describe.**
OpenSearch plugins would like to send alerts over to the alerting plugin. An RFC will be generated to gather community feedback.

The current Alerting plugin has no framework or API for other plugins to integrate with Alerting. While Anomaly Detection (AD) plugin has integrated with Alerting, it is through tightly coupling their code base with the Alerting code base. This is a sub-optimal design as this causes friction whenever there are new changes for Alerting or AD. We will build a framework and API to allow for other plugins to integrate with Alerting with a new feature called Push Alerts. Push Alerts will allow other plugins to send/push relevant alerts to the alerting plugin while taking advantage of the features like throttling and action support (sending notifications using the notification plugin).

Requirements:
- We need to allow other plugins call Alerting through an API to push alerts to Alerting (including bulk support)
- Need to be able to abstract out Alerts from Monitors and triggers since the other plugins will generate the alerts and they won’t be associated to any monitor or trigger
- We need to be able to associate the alerts to the plugin that is generating them
 - Should be viewable in Alerting plugin 
 - Should be able to categorize different sets of alerts that come from one plugin
  - For example, AD has multiple monitors, the alerts generated from 1 monitor should be grouped together while the alerts generated from another monitor should be grouped separately
    * If we can tag alerts, this can be used to bucket the different alerts generated from other plugins
* Need to allow the other plugins to setup action configurations for when alerts are being generated
    * For example, AD sends twenty alerts to us. AD has set it up so it would send notifications to a chime webhook. Also AD can set it up to throttle the actions, so notifications can only go out once every 10 minutes
* (Possible scope) Allow users to setup action configurations for alerts with a certain tag

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by brijos** [comment]
Referencing https://github.com/opensearch-project/alerting/issues/107

**Comment by brijos** [comment]
https://github.com/opensearch-project/alerting/issues/107

**Comment by lezzago** [comment]
Important notes:
- Scaling will be a concern and to publish alerts at 1000 TPS would not be possible for the plugin based on OpenSearch plugin architecture. 
- There may need to be 2 approaches, a simple API approach and another is to use doc level monitor as a pass through monitor to quickly generate alerts and enhancements need to be made to it to better support this use case (can be done by UI side)
