### ISSUE TITLE
More logging

### ISSUE THREAD

**Issue by adityaj1107** [opensearch-project/alerting#41]
<a href="https://github.com/lucaswin-amzn"><img src="https://avatars.githubusercontent.com/u/46609415?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lucaswin-amzn](https://github.com/lucaswin-amzn)**
_Monday Jul 01, 2019 at 22:08 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/alerting/issues/77_

----

We are currently missing some logging information around trigger evaluation, and in general we could improve debug capability for users with more logging. 

[See here for an example](https://discuss.opendistrocommunity.dev/t/kibana-alerting-randomly-triggering-no-data-returned/973/3)

**Comment by engechas** [comment]
Closing as resolved by #1223
