### ISSUE TITLE
Create shared parent class for HttpInputClient and DestinationHttpClient

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/alerting#44]
<a href="https://github.com/ann3431"><img src="https://avatars.githubusercontent.com/u/27038367?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ann3431](https://github.com/ann3431)**
_Friday Jul 19, 2019 at 22:20 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/alerting/issues/87_

----

`HttpInputClient` and `DestinationHttpClient` has duplicate functionalities. We should create a shared parent class for these two.

**Comment by qreshi** [comment]
Closing this since HttpInput eventually became the LocalUriInput feature which is currently in [PR](https://github.com/opensearch-project/alerting/pull/221) and this issue no longer applies there.
