### ISSUE TITLE
How to Limit Access to Alerting Plugin

### ISSUE THREAD

**Issue by sevenval-admins** [opensearch-project/alerting#460]
**Is your feature request related to a problem? Please describe.**
Hi guys, I have the following problem: I was testing the Alerting plugin and as stated in the [documentation](https://opensearch.org/docs/latest/monitoring-plugins/alerting/security/#advanced-limit-access-by-backend-role), basically every monitor and destination that is created is visible to every user, except if the following setting is applied:
```
PUT _cluster/settings
{
  "transient": {
    "plugins.alerting.filter_by_backend_roles": "true"
  }
}
```
With this option it is possible depending on the backend role to restrict the display of monitors and destinations.
My OpenSearch is connected to a LDAP-Server and in my company there are hundreds of AD-Groups which my OpenSearch resolves all as backend roles. All of us in the company share several AD-Groups and as specified in the documentation the separation of monitors and destinations only works if no backend role is shared. 
Setting the resolve_nested_roles option to false excludes all roles that are nested but still leaves several that are not.
Even if I use the [nested_role_filter](https://opensearch.org/docs/latest/security-plugin/configuration/ldap/#advanced-exclude-roles-from-nested-role-lookups) parameter this only applies to nested roles and leaves out all those that are not. 

**Describe the solution you'd like**
It would be a great improvement to have the possibility to separate the Monitoring and Destinations  according to Tenant or to really be able to filter out all unnecessary roles.

Thanks in advance to anyone wo will take a look into it.

**Comment by sevenval-admins** [comment]
A Feature Request was opened at Alerting-Plugin project: https://github.com/opensearch-project/alerting/issues/459
I think we can close the issue here @adnapibar ?

**Comment by lezzago** [comment]
I will close this issue in favor of #459 and #138, which is the original issue to track this problem.
