### ISSUE TITLE
[BUG] "Failed to update the monitor" after updating existing monitor config (and selecting notification channel)

### ISSUE THREAD

**Issue by olwe0002** [opensearch-project/alerting#470]
After updating to Opensearch 2.0.0 (via Helm Chart 2.0.1), there is a new error in place:

On updating an existing monitor config, e.g. selecting a channel on a notification entry and click on "Update", the following message occurs:

`[illegal_state_exception] Can't get text on a START_OBJECT at 1:1552`
depending on the monitor config sometimes a different line number:
`[illegal_state_exception] Can't get text on a START_OBJECT at 1:1536`

steps to reproduce:

1. open existing monitor config and click "Edit"
2. scroll down to the triggers and extend the actions. Note that the "Channel" field is filled out with a channel name
3. do not change anything and click on "Update"
4. the error message occurs
5. reload the page
6. scroll down to the triggers and extend the actions. Note that the "Channel" field is NOT filled out any more (now: "Select Channel to notify")
7. click on "Update"
8. message `Fix all highlighted error(s) before continuing.` comes up
9. select a channel (hard to do, several clicks are needed, leaving the field seems to trigger the stuff!)
10. click on "Update" again. Sometimes it works, depending on how you selected the channel maybe. Can't tell in which cases.

So it seems like its related to the change from Alerting Destinations to Notifications Channels. Please have a look

**Comment by theanotherwise** [comment]
deni with Fix:

https://github.com/seemscloud/docker-opensearch-2.0.0-fix-demo

**Comment by lezzago** [comment]
@olwe0002, if you update your cluster to 2.0.1, the issue will be resolved as it contains the fix.

**Comment by kksaha** [comment]
While updating the monitor, even if we are using version 2.2.0, the problem persists.
<img width="651" alt="image" src="https://user-images.githubusercontent.com/34137960/212682232-ed87d1b4-3b93-46ca-88f3-bcd9fa492913.png">
