### ISSUE TITLE
[FEATURE] Support multiple indices as input for Document level monitors

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/alerting#474]
**Is your feature request related to a problem?**
Currently document level monitors will only monitor the first index inputted for the configuration of the monitor instead of all of the indices inputted to it.

**What solution would you like?**
The document level monitor must know support monitoring multiple indices at once.

**Do you have any additional context?**
This is the [area](https://github.com/opensearch-project/alerting/blob/main/alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt#L98) where the document level monitor will only take the first index inputted to it.

**Comment by engechas** [comment]
Multiple indices are now supported. Closing
