### ISSUE TITLE
[BUG] Define monitor match type phrase does not work

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/alerting#49]
<a href="https://github.com/stefaneg"><img src="https://avatars.githubusercontent.com/u/140227?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [stefaneg](https://github.com/stefaneg)**
_Tuesday Sep 24, 2019 at 16:47 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/alerting/issues/108_

----

**Describe the bug**
When copy-pasting a query from Kibana-Discover to the "Define extraction query" field containing match:{type:phrase}, Extraction query response only shows quotes, and no feedback at all on what went wrong.

**To Reproduce**
View your data/logs in Discover. Put a restriction on any text field. Copy the query DSL. Paste into Define extraction query. You get no results.

**Expected behavior**
Extraction query response should give me the same results as in the Discover view in Kibana.

**Version:**
Kibana 6.2.3, aws hosted.

**Additional context**
In some example I came across the "match_phrase" syntax which does work. This however is rather ridiculous to have one syntax work in one place of the interface and not the other. Expecially when there is no parsing or error feedback AT ALL in the Define Monitor UI, which maybe warrants a separate bug report. This was trial and error pretty much in the dark to find out why on earth the match syntax was not working.

This does not work (Copy paste DSL from Discover interface), and fails silently:
```
{
  "query": {
    "match": {
      "kubernetes.host": {
        "query": "kube-p03",
        "type": "phrase"
      }
    }
  }
} 
```

This works:
```
{
  "query": {
    "match_phrase": {
      "kubernetes.host": {
        "query": "kube-p03"
      }
    }
  }
} 
```

**Comment by aditjind** [comment]
<a href="https://github.com/lucaswin-amzn"><img src="https://avatars.githubusercontent.com/u/46609415?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lucaswin-amzn](https://github.com/lucaswin-amzn)**
_Monday Sep 30, 2019 at 20:46 GMT_

----

Thanks @stefaneg,

It appears that there is a discrepancy between the parser used from the Kibana discover page and what is actually parsed on the backend of Elasticsearch. We will take a look at this.

I also agree that there needs to be more error feedback from the Kibana UI.

**Comment by uroskarama** [comment]
@aditjind  @praveensameneni  
I have tried to reproduce this on the latest version (2.4.0) of OpenSearch by doing following steps:
1. Created a filter in Discover on a single field, got correct results in discover
2. Copied the generated query from Inspect -> Request tab and pasted into Extraction query editor when creating a monitor, and running the query.
I have received the correct response from running the query, same as the one in discover.
I think this is the correct behavior?

**Comment by sandeshkr419** [comment]
@aditjind @praveensameneni Can we check if this issue is closed in recent versions of OpenSearch as @uroskarama commented.
If yes, lets close this with relevant information regarding when is this fixed.

**Comment by lezzago** [comment]
I was not able to replicate this issue on OpenSearch 1.0. There may have been changes to OpenSearch-Dashboard's parser to keep in in sync with OpenSearch when it was launched. 

As this issue has been non-existent to all the version we actively support, will close the issue.
