### ISSUE TITLE
Implement OpenSearch core branching strategy

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/alerting#493]
### Description

Ensure `MAJOR_VERSION.x` branch exists, the `main` branch acts as source of truth effectively working on 2 versions at the same time.

### Related META issue

https://github.com/opensearch-project/opensearch-plugins/issues/142

### Current Behavior

Currently plugins follow a branching strategy where they work on `main` for the next development iteration, effectively working on 2 versions at the same time. This is not always true for all plugins, the release branch or branch pattern is not consistent, the lack of this standardization would limit multiple automation workflows and alignment with core repo. More details on [META ISSUE](https://github.com/opensearch-project/opensearch-plugins/issues/142)

### Proposed solution

Follow OpenSearch [core branching](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#opensearch-branching). Create `1.x` and `2.x` branches, do not create `2.0` as a branch of main, instead create `main -> 2.x -> 2.0`. Maintain working CI for 3 releases at any given time.

**Comment by lezzago** [comment]
The `1.x` and `2.x` branches are available. To push `main` to `3.0`, the `notification` plugin needs to be updated to `3.0` and then we need `ci.opensearch.org` to contain the notification 3.0 build.

**Comment by prudhvigodithi** [comment]
Hey @lezzago can you please post an update on this branching alignment? also can you make sure, this branching is followed for future releases as well?
Thank you 
@bbarani @dblock @CEHENKLE

**Comment by lezzago** [comment]
@prudhvigodithi, we will make sure this branching strategy is followed in future releases. Once we launch 3.0, we will make sure to update the version of the main branch to 4.0. 

Also currently we are blocked from updating main to 3.0 until Notification updates to 3.0

**Comment by dblock** [comment]
There should be nothing blocking notifications anymore, please go run that one down.

To close this issue:

- [ ] main is building 3.0
- [ ] 2.x is building next 2.x, which is currently 2.4.0
- [ ] 2.3 is building next 2.3, which is 2.3.1
- [ ] manifests in https://github.com/opensearch-project/opensearch-build/tree/main/manifests include all 3

**Comment by lezzago** [comment]
Currently this is blocked by notification and that is blocked by PA since PA doesnt build against 3.0 successfully and causes the docker to not come up which is needed for the Notification plugin to run the security tests.

**Comment by lezzago** [comment]
Current blockers:
https://github.com/opensearch-project/opensearch-build/issues/2886
https://github.com/opensearch-project/opensearch-build/issues/2868

**Comment by dblock** [comment]
@lezzago These were fixed.

**Comment by bbarani** [comment]
@lezzago Can you provide updated status of this issue?

**Comment by bbarani** [comment]
@lezzago @praveensameneni @opensearch-project/alerting-plugin  Can you update this issue with current status?

**Comment by lezzago** [comment]
The alerting PR has been merged
