### ISSUE TITLE
Add HTTP method option on custom webhook

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/alerting#51]
<a href="https://github.com/raymanound"><img src="https://avatars.githubusercontent.com/u/58698476?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [raymanound](https://github.com/raymanound)**
_Sunday Dec 29, 2019 at 16:45 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/alerting/issues/136_

----

The custom webhook can only send the HTTP POST request by default. I think adding HTTP method as a option is helpful since many services API are using other HTTP methods as well like using PUT for update action.

**Comment by qreshi** [comment]
Closing this as `POST`, `PUT` and `PATCH` are already supported (added in this [change](https://github.com/opendistro-for-elasticsearch/alerting/pull/101))
