### ISSUE TITLE
[RFC] Composite Monitors 

### ISSUE THREAD

**Issue by eirsep** [opensearch-project/alerting#524]
**Challenges in Status Quo**
Today Alerting is not an optimal framework to be used by other consumers including as Anomaly Detection (AD) and Security Analytics (SA). There is a hard coupling of data configuration and execution of monitors, triggers and alerts in codebase. Currently users can’t decide where to persist alerts, findings for different sets of data.

The current monitor types - Query Level , Bucket Level, Document level and Cluster metrics monitors - are constrictive in nature and each of them only supports an individual trigger type. For instance, Bucket level monitors are fashioned such that one can only create triggers based on aggregations and  Doc level monitors can only send triggers per document level. There is no way we can combine or chain their capabilities to write more complex queries, monitor more complex workloads or create more nuanced triggers/alerts.

 These monitors support specific types of queries and corresponding triggers but users have workloads which need to be queried in a more complex fashion. The execution workflow for these monitors are very coupled with their direct functional needs. The data sources for both reads and writes are hard coded, with assumption that they would always remain same from the Alerting purview. 

**Composite Monitors**

Composite monitors allow user to chain execution of multiple monitors of different types into a single flow. This is useful in the scenario where the analysis and findings of one monitor would be the input/source data of another monitor and so on. Another advantage is to have a single view of data source during the monitor execution run to be fanned out across multiple monitors, to attain finer consistency of results.  Such chaining would also facilitate creating triggers on different aspects of data. For instance, users would be able to create a monitor that could create both bucket level and doc level triggers on the same data without having to worry about coordinating the data set being used as a source for each monitor to be the same. This facilitates dicing and slicing of data and define triggers and alerts based on a combination of diverse set of rules. Had it been left to the user to coordinate the execution of 2 monitors, they would have to worry about scheduling monitors in a deterministic order which is not guaranteed in Alerting plugin design.

Composite monitors allow users to execute delegate monitors in sequential fashion hence providing more control over the data seen by chained monitors i.e. we can guarantee that the monitors using data from another delegate monitor’s findings in the same run. 

A composite monitor would consist of multiple “delegate” monitors(Document/bucket/query level monitors) which need to be created beforehand and defined in the composite monitor’s “execution schema”. The delegate monitors would be executed in the sequence defined at creation time and would accept overridden parameters for data source, rules/query index, triggers and alerts. Users must create document/bucket/query level monitors beforehand (in disabled mode if user doesn’t wish to run the monitor independently) and reference the monitors by their id’s along with custom parameters to override and define data source, rules source, config for triggers and alerts.

**Comment by getsaurabh02** [comment]
@eirsep Can we list down some use cases to illustrate the problem statements around this? It will help to identify the ask for the composite monitors.

**Comment by getsaurabh02** [comment]
//cc @brijos to bring in product perspective and ideas.

**Comment by eirsep** [comment]
https://github.com/opensearch-project/alerting/issues/834
