### ISSUE TITLE
Send notification on completed alerts

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/alerting#55]
<a href="https://github.com/NikitaGl"><img src="https://avatars.githubusercontent.com/u/17144525?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [NikitaGl](https://github.com/NikitaGl)**
_Friday Feb 21, 2020 at 11:59 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/alerting/issues/169_

----

**Is your feature request related to a problem? Please describe.**
We have several monitors configured, which send a slack notification on alerting state. Ops team gets involved, maintenance/troubleshooting/etc happens and issue is resolved, but Completed state of alert could only be manually checked through Kibana. 
**Describe the solution you'd like**
It would be great to receive an OK notification for alert, like it is implemented in [Grafana Alerting](https://grafana.com/docs/grafana/latest/alerting/rules/).

**Describe alternatives you've considered**
For now, we us alerts as is, just moved slack notifications to ops-team channel, where all participants are eligible to check status manually.

**Comment by aditjind** [comment]
<a href="https://github.com/skkosuri-amzn"><img src="https://avatars.githubusercontent.com/u/59816283?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [skkosuri-amzn](https://github.com/skkosuri-amzn)**
_Saturday Nov 28, 2020 at 23:52 GMT_

----

Linking duplicate: https://github.com/opendistro-for-elasticsearch/alerting/issues/277

**Comment by qreshi** [comment]
Closing this issue in favor of #31 as it also relates to notifying on state change.
