### ISSUE TITLE
[BUG] Ensure Alerting CI is running ktlint

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/alerting#573]
[BUG] Ensure Alerting CI is running ktlint.

Upgrade ktlint to 0.47.0 to resolve max-length issues on Windows and LINUX (rare)
https://github.com/pinterest/ktlint/issues/1496#issuecomment-1223979084
https://github.com/opensearch-project/alerting/issues/557#issuecomment-1259848896

As of now we have disabled ktlint on both the assemble and publishingzips task to avoid error.

Thanks.

**Comment by dblock** [comment]
We should be doing this as part of https://github.com/opensearch-project/alerting/issues/214

**Comment by praveensameneni** [comment]
Closing the issue as the code has been merged
