### ISSUE TITLE
Error: Failed fetching inputs: org.opensearch.OpenSearchSecurityException: no permissions for [indices:data/read/search] and associated roles

### ISSUE THREAD

**Issue by ARud12** [opensearch-project/alerting#625]
When deploying an alert and the monitor is triggered, the following error is seen: Error: Failed fetching inputs: org.opensearch.OpenSearchSecurityException: no permissions for [indices:data/read/search] and associated roles 
The alert then goes into an error state and cannot be acknowledged.

**Comment by lezzago** [comment]
Clone of this issue: https://github.com/opensearch-project/alerting-dashboards-plugin/issues/353
