### ISSUE TITLE
Support document level alerts

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/alerting#63]
<a href="https://github.com/praveensameneni"><img src="https://avatars.githubusercontent.com/u/50342543?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [praveensameneni](https://github.com/praveensameneni)**
_Tuesday Jun 09, 2020 at 06:26 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/alerting/issues/211_

----

**Comment by qreshi** [comment]
Closing this since it's a duplicate of #86 which has launched.

There is also an existing planned feature for Document-Level Alerting which is being tracked in #238
