### ISSUE TITLE
Support chained alerts

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/alerting#64]
<a href="https://github.com/praveensameneni"><img src="https://avatars.githubusercontent.com/u/50342543?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [praveensameneni](https://github.com/praveensameneni)**
_Tuesday Jun 09, 2020 at 06:49 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/alerting/issues/212_

----

**Comment by qreshi** [comment]
Closing this issue since it looks like #36 and #37 are proposing a similar enhancement to this.
