### ISSUE TITLE
Support multiple queries while define monitor

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/alerting#66]
<a href="https://github.com/seraphjiang"><img src="https://avatars.githubusercontent.com/u/550437?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [seraphjiang](https://github.com/seraphjiang)**
_Wednesday Jul 08, 2020 at 19:11 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/alerting/issues/221_

----

Scenario:

I want to setup an alerting, the trigger expression like below

```
ctx.results[0].aggregations.issueCount.value > ctx.results[1].aggregations.averageCountInPast7Days.value
```

the first aggregation is just count in current internval (now-interval ~ now)
the second aggregation is average of count(not  average of value) in (now-7Days ~ now)

i'm not able to come up a ES query which could achieve my goal .

with current Alerting, i could only given a hard code fix number, it is not very useful in real case.
ctx.results[0].aggregations.issueCount.value > 1800

support multiple queries while define monitor could meet our need. Also this will enable a lot of possibility and use cases.

we are also open for suggestion if this could be done in one query.

**Comment by aditjind** [comment]
<a href="https://github.com/dbbaughe"><img src="https://avatars.githubusercontent.com/u/46505179?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dbbaughe](https://github.com/dbbaughe)**
_Tuesday Jul 14, 2020 at 00:38 GMT_

----

This is possible, just not currently allowed.

There is an arbitrary limit set to 1 from these two places:

https://github.com/opendistro-for-elasticsearch/alerting/blob/master/alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/settings/AlertingSettings.kt#L29

https://github.com/opendistro-for-elasticsearch/alerting/blob/b0e29132a62eddd79784547916a7c16532134e67/alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/Monitor.kt#L70

Unfortunately it's hard coded right now so you can't change it for a live domain. But, I did test locally and it worked by querying two indices and having the two different responses available on the ctx variable. Before this can be changed we'd need to get a Kibana UI to support multiple queries though.

**Comment by aditjind** [comment]
<a href="https://github.com/seraphjiang"><img src="https://avatars.githubusercontent.com/u/550437?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [seraphjiang](https://github.com/seraphjiang)**
_Tuesday Jul 14, 2020 at 00:58 GMT_

----

That's awesome.

Could we release a version with backend support. I assume we could use API to create multiple queries monitor we want. 

We are good without UI ^_^

**Comment by aditjind** [comment]
<a href="https://github.com/dbbaughe"><img src="https://avatars.githubusercontent.com/u/46505179?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dbbaughe](https://github.com/dbbaughe)**
_Tuesday Jul 14, 2020 at 01:21 GMT_

----

Yes, it would work directly through API. Unfortunately I don't believe we can release it without the Kibana UI as multiple search inputs might break the UI in the worst case or severely limit user experience in the best case. We'll have to work with UI/UX team to get the needed designs to implement the multiple input support on Kibana first.

**Comment by aditjind** [comment]
<a href="https://github.com/seraphjiang"><img src="https://avatars.githubusercontent.com/u/550437?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [seraphjiang](https://github.com/seraphjiang)**
_Tuesday Jul 14, 2020 at 05:03 GMT_

----

Got it, thanks for explanation.

**Comment by aditjind** [comment]
<a href="https://github.com/manuasir"><img src="https://avatars.githubusercontent.com/u/10210567?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [manuasir](https://github.com/manuasir)**
_Thursday Jul 30, 2020 at 10:20 GMT_

----

Waiting for this to be released ASAP!

**Comment by qreshi** [comment]
Closing this in favor of #80 to avoid duplication.
