### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by divyankm** [opensearch-project/alerting#701]
**What is the bug?**
When creating per bucket alerting monitors, the extraction visual editor query drop-down of groupby is not able to add `field` in Index. When click on groupby button, getting a notification `you have selected all available options` and not able to add a field in `group by` dropdown.

Snap:

![image](https://user-images.githubusercontent.com/80899863/207565496-5f5382fb-5a84-4ad2-a117-9ad76fb57656.png)

![image](https://user-images.githubusercontent.com/80899863/207565853-d0437d56-897d-4413-bb71-d3030d095d43.png)

**How can one reproduce the bug?**

1. Go to Alerting, create monitor.
2. Select per bucket monitor.
3. Select visual query editor.
4. Go to Groupby Section and try to add field in groupby
5. Will get notification: `you have selected all available options` and I could not able to add field due to which cannot create monitor using `visual editor` method. 

**What is the expected behavior?**

**What is your host/environment?**
 - OS: Windows 10 (Docker Desktop)
 - Version: 2.0.0
 - Plugin : Alerting

**Comment by lezzago** [comment]
Closing this as this issue is currently open on the dashboard alerting plugin: https://github.com/opensearch-project/alerting-dashboards-plugin/issues/291
