### ISSUE TITLE
[BUG] Mixed use of scheduledRollover variable for both alert history index and finding history index. 

### ISSUE THREAD

**Issue by heemin32** [opensearch-project/alerting#703]
**What is the bug?**
`scheduledRollover` variable is used for both alert history index rollover task and finding history index rollover task. Consequently, canceling of the scheduled task won't work correctly when cluster manager node is changed.

**How can one reproduce the bug?**
https://github.com/opensearch-project/alerting/blob/main/alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt#L175

**What is the expected behavior?**
We should maintain two variable for each task

**What is your host/environment?**
N/A

**Do you have any screenshots?**
N/A

**Do you have any additional context?**
N/A

**Comment by lezzago** [comment]
PR merged
