### ISSUE TITLE
[Bug] Support overriding defaultTitle for Notifications send via Alerting

### ISSUE THREAD

**Issue by AWSHurneyt** [opensearch-project/alerting#731]
**Is your feature request related to a problem?**
When the migration of destinations to the Notifications plugin that happened in OS 2.0, the `subject` line of migrated Alerting trigger action messages have been replaced with the `defaultTitle` "Alerting-Notification Action" when using SNS to send the emails. The old `subject` line then appears in the message `body`.

**What solution would you like?**
Ideally, if a `subject` line is populated, Notifications should use that for the email subject instead of the `defaultTitle`.

**Workarounds**
1. Users can setup an `SES Notification Channel` which takes in the `title` as the `subject`.

**Comment by qreshi** [comment]
Transferred this issue to the Alerting plugin repo as that's where the defaultTitle override needed to occur.

**Comment by qreshi** [comment]
Closing issue as the change has been merged in.
