### ISSUE TITLE
Ability to iterate over the list of hits, and send alert with multiple values

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/alerting#75]
<a href="https://github.com/vinaymorkar"><img src="https://avatars.githubusercontent.com/u/26841808?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vinaymorkar](https://github.com/vinaymorkar)**
_Tuesday Oct 13, 2020 at 06:22 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/alerting/issues/267_

----

**Problem:**
I have multiple servers with metricbeat running on each of them. All the servers push the metric data on one index. Now if more than one servers exceed the set threshold I should get an alert with the name of the servers and the values they breached.

**Solution I would like to have**
There should be a way to iterate over the hits and create a map with key-value pairs that will contain the name and values of the servers and their breached values. Then i should be able to store this map in a variable that can be passed in the alert message.

**Comment by qreshi** [comment]
Hey @vinaymorkar,

As of OpenSearch 1.1, we have introduced [Bucket-Level Monitors](https://opensearch.org/docs/latest/monitoring-plugins/alerting/api/#create-bucket-level-monitor) where you can define your monitor to group by your servers and create Alerts on each server which meets your conditions.

Try it out and see if satisfies your use case.

**Comment by qreshi** [comment]
Closing this as the feature enhancement mentioned above should be able to accomplish this. Feel free to re-open if there are any concerns.
