### ISSUE TITLE
[BUG] QueryIndex rollover-ing indefinitely 

### ISSUE THREAD

**Issue by petardz** [opensearch-project/alerting#775]
**What is the bug?**
When source index has more fields in mappings then query index max_field limit (1000) then queryIndex would rollover and error for every monitor run, indefinitely.

**How can one reproduce the bug?**
1. Create index with 1000+ fields in mappings
2. Create DocLevel Monitor on this index
3. Observe query index being rolled over on every run and monitor erroring

**What is the expected behavior?**
We should adjust query index max fields limit in this situation, so that it can have at least the same number of fields in mappings like source index

**What is your host/environment?**
 - Version 2.5

**Comment by lezzago** [comment]
PR is merged
