### ISSUE TITLE
Create Monitor- Multiple where clauses in Visual Graph option

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/alerting#83]
<a href="https://github.com/taha2009"><img src="https://avatars.githubusercontent.com/u/3643983?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [taha2009](https://github.com/taha2009)**
_Monday Nov 30, 2020 at 11:32 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/alerting/issues/307_

----

**Is your feature request related to a problem? Please describe.**
Currently while creating a monitor, while using visual graph option I can give a where clause, for our purposes we want user to be able to give more filters (Where clauses)

**Describe the solution you'd like**
Please provide option for user to create multiple where clauses (Filter)

**Describe alternatives you've considered**
For now we are planning to add a textarea where user can provide lucene queries for more detailed searches.

**Additional context**
N/A

**Comment by qreshi** [comment]
Hey @taha2009,

As of OpenSearch 1.1, we've refactored the Alerting frontend experience and this includes adding multiple where clauses (which is now labeled as `"Data filter"`).

You can see an example of what it looks like in the demo included in [this PR](https://github.com/opensearch-project/alerting-dashboards-plugin/pull/44) but I suggest trying it out for yourself.
