### ISSUE TITLE
[BUG] multiple filter alerting api

### ISSUE THREAD

**Issue by Realcheese94** [opensearch-project/alerting#842]
Hi,
I am using for "/_plugins/_alerting/monitors/alerts"

But, I should filter this Result,

So I try this
/_plugins/_alerting/monitors/alerts?monitorId=
/_plugins/_alerting/monitors/alerts?alertState=

But I can't like this (monitorId value is sample data)
/_plugins/_alerting/monitors/alerts?monitorId=dfsafsfsfsa&alertState=COMPLETED

Is this bug? or not yet?
I want to mutiple filter in using plugins

plz... help me

**Comment by lezzago** [comment]
Can you share which OpenSearch version you are utilizing?

**Comment by lezzago** [comment]
I am seeing similar issues on OpenSearch 2.6

**Comment by lezzago** [comment]
Closing this as the PRs have been merged.
