### ISSUE TITLE
Alert on anomaly with category-field - "No data to display" in trigger

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/alerting#88]
<a href="https://github.com/NicoP-S"><img src="https://avatars.githubusercontent.com/u/8988747?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [NicoP-S](https://github.com/NicoP-S)**
_Monday Jan 04, 2021 at 08:15 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/alerting/issues/332_

----

**Describe the bug**
If i try to add an alert to our anomaly detection with category field the alert trigger always says "No data to display".
The anomaly detector works. It's running and it  does find anomalies.
Opendistro version: 1.12.0

![grafik](https://user-images.githubusercontent.com/8988747/103514356-bda3df80-4e6c-11eb-8495-c485ebed31b0.png)

**To Reproduce**
1) Setup anomaly detector and add category-field
https://opendistro.github.io/for-elasticsearch-docs/docs/ad/#optional-set-a-category-field-for-high-cardinality
2) Add Alert for the detector 
3) the trigger always says no data
![grafik](https://user-images.githubusercontent.com/8988747/103514473-fe035d80-4e6c-11eb-9e36-59ae856c37ca.png)

I don't know if this is this a configuration problem on my side or a bug.

**Comment by qreshi** [comment]
Hey @NicoP-S,

Just to clarify, are you saying the "No data to display" in the frontend during creation of the Trigger is the problem or does the created Trigger also never Alert because it is not meeting the conditions?

**Comment by NicoP-S** [comment]
Hi, 
alerts were triggered. Just the frontend wasn't showing any data in the trigger configuration. 
It's some time ago... we don't use this trigger anymore. 
If noone else had reported this problem, closeing this issue would be ok for me.
