### ISSUE TITLE
Include Microsoft Teams as destination

### ISSUE THREAD

**Issue by jeferson-cleancloud** [opensearch-project/alerting#916]
**Is your feature request related to a problem?**
Custom Webhook does not support Microsoft Teams webhooks.

**What solution would you like?**
Include support for Microsoft Teams as destination, or include a possibility to run an script to convert the text body into different payload.

**What alternatives have you considered?**
Using SNS + Lambda but it is lot of to maintain just for alerting purpose

**Do you have any additional context?**
Include support for Microsoft Teams as destination

**Comment by lezzago** [comment]
This is all owned by the Notification plugin. There is a feature request for that there: https://github.com/opensearch-project/notifications/issues/585
