### ISSUE TITLE
[BUG] Failed to get findings exception for per-document monitor

### ISSUE THREAD

**Issue by nik06** [opensearch-project/alerting#977]
**What is the bug?**
Exception while trying to see Document findings for a monitor

**How can one reproduce the bug?**
1. Create a per-document monitor
2. Satisfy the condition so that an alert is raised and document finding is created.
3. Open the Monitor page and go to Document Findings tab.
4. Exception comes up even though you can see Alerts raised in Alerts tab

**What is the expected behavior?**
The monitor should show all the Document findings

**What is your host/environment?**
 - OS: Windows 10
 - Version : Opensearch2.8.0
 - Plugins

**Do you have any screenshots?**
Alerts Tab :
![image](https://github.com/opensearch-project/alerting/assets/9622201/f2f86470-545f-4b60-be46-d3d2d81a8f2c)
Document Findings Tab :
![image](https://github.com/opensearch-project/alerting/assets/9622201/070f28d5-8bcf-4b61-9e95-332f9a1347ad)

**Do you have any additional context?**
No

**Comment by riysaxen-amzn** [comment]
@nik06 followed the steps you mentioned above in version 2.8, but I wasn't able to reproduce the exception. `all shards failed `is an OpenSearch exception and it comes when the shards were failed while serving a request(query or index). In this case the exception came when a search req is made to get the document findings. Please check the index/cluster state and let us know if you're still seeing this issue.
