### ISSUE TITLE
ctx.alert.isAcknowledged not accessible with trigger

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/alerting#99]
<a href="https://github.com/rini2208"><img src="https://avatars.githubusercontent.com/u/83286730?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rini2208](https://github.com/rini2208)**
_Thursday Apr 29, 2021 at 08:19 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/alerting/issues/371_

----

IN openDistro kibana ctx.alert.isAcknowledged variable to accessible , giving error as
"caused_by" : {
    "type" : "illegal_argument_exception",
    "reason" : "field [com.amazon.opendistroforelasticsearch.alerting.model.Alert, isAcknowledged] not found"
  }

**Comment by qreshi** [comment]
Closing this in favor of #200 for tracking in a single place
