### ISSUE TITLE
[Backports failed] Fix getAlerts RBAC problem

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/alerting#996]
Backports for this PR failed, this issue can be closed once all backports are completed.
https://github.com/opensearch-project/alerting/pull/991

**Comment by lezzago** [comment]
2.9 backport PR: #1000 
2.8 backport PR: #999 
2.7 backport PR: #998

**Comment by sbcd90** [comment]
closing this issue. @lezzago plz let us know if anything pending here.
